> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  
function2 = np.transpose 
function3 = np.vstack
function4 = np.hstac
function5 = np.split

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [ ]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

Explanation about example

In [13]:
np.shape(arr1)

(2, 2)

In [14]:
np.shape(arr2)

(2, 3)

When concatenating arrays along the columns (axis=1), the arrays need to have the same number of rows. In this case, arr1 has 2 rows and arr2 also has 2 rows, so they can be concatenated along the columns.

In [20]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9],[7,5]]

np.concatenate((arr1, arr2), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [8., 9.],
       [7., 5.]])

Explanation about example

In this case, arr1 and arr2 have different numbers of rows (2 and 3, respectively), but they have the same number of columns (2), which allows concatenation along axis=0 (rows). 

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

it breaks with a ValueError because the shapes of the two arrays are not compatible for concatenation along axis=0.
arr1 has shape (2 rows and 2 columns)and arr2 has shape (2 rows and 3 columns)
The error message states: "all the input array dimensions for the concatenation axis must match exactly." This means that the arrays being concatenated must have the same shape along the specified axis.

Some closing comments about when to use this function.

## Function 2 - np.transpose

Add some explanations

In [22]:
arr1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# Example 1 - working
function2 = np.transpose(arr1)
function2

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Explanation about example

in this example arr1 have 3 rows and 4 columns. When we take the transpose of arr1, the rows will convert into columns and the columns will convert into rows. The resulting transposed array will have 4 rows and 3 columns

In [56]:
# Example 2 - working
arr2 = [[5, 6, 7], 
        [8, 9, 10]]
np.transpose(arr2)

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

Explanation about example

in this example arr2 have 2 rows and 3 columns. When we take the transpose of arr2, the rows will convert into columns and the columns will convert into rows. The resulting transposed array will have 3 rows and 2 columns

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr4 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [53]:
transposed_arr = np.transpose(arr5)
print(transposed_arr)

NameError: name 'arr5' is not defined

Explanation about example (why it breaks and how to fix it)

he variable arr5 is not defined anywhere, which causes the NameError. The variable name should be arr4, which is the array we defined previously.

Some closing comments about when to use this function.

## Function 3 - np.vstack

Add some explanations

In [64]:
# Example 1 - working
a = [[1, 2], 
    [3, 4.]]

b = [[10, 2], 
    [3, 40.]]

In [65]:
np.vstack((a, b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [10.,  2.],
       [ 3., 40.]])

Explanation about example

In [66]:
# Example 2 - working
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
arr3

array([[2, 3, 4, 5],
       [6, 1, 8, 9],
       [1, 5, 7, 3]])

In [68]:
np.vstack((arr1,arr3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  3,  4,  5],
       [ 6,  1,  8,  9],
       [ 1,  5,  7,  3]])

Explanation about example

In [75]:
# Example 3 - breaking (to illustrate when it breaks)
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
r=np.array([[3,4],[6,7]])
np.vstack((w,r))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

Explanation about example (why it breaks and how to fix it)

This error occurs when we try to vertically stack two arrays with different numbers of rows. it seems that we're trying to vertically stack a 3x3 array with a 2x2 array.
To fix this error, you need to make sure that the number of rows in both arrays are the same.

Some closing comments about when to use this function.

## Function 4 - np.hstack

Add some explanations

In [70]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
arr3

array([[2, 3, 4, 5],
       [6, 1, 8, 9],
       [1, 5, 7, 3]])

In [72]:
# Example 1 - working
np.hstack((arr1,arr3))

array([[ 1,  2,  3,  4,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  6,  1,  8,  9],
       [ 9, 10, 11, 12,  1,  5,  7,  3]])

Explanation about example

In [73]:
# Example 2 - working
a = [[1, 2], 
    [3, 4.]]

b = [[10, 2], 
    [3, 40.]]

np.hstack((a, b))

array([[ 1.,  2., 10.,  2.],
       [ 3.,  4.,  3., 40.]])

Explanation about example

In [74]:
# Example 3 - breaking (to illustrate when it breaks)
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
r=np.array([[3,4],[6,7]])
np.hstack((w,r))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

Explanation about example (why it breaks and how to fix it)

This error occurs when we try to horizontally stack two arrays with different numbers of rows. it seems that we’re trying to horizontally stack a 3x3 array with a 2x2 array.
To fix this error, you need to make sure that the number of rows in both arrays are the same. 

Some closing comments about when to use this function.

## Function 5 - np.split

Add some explanations

In [80]:
# Example 1 - working
a1=np.arange(1,10)
np.split(a1,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Explanation about example

In [83]:
# Example 2 - working
x=np.hstack((arr1,arr3))
np.split(x,3)

[array([[1, 2, 3, 4, 2, 3, 4, 5]]),
 array([[5, 6, 7, 8, 6, 1, 8, 9]]),
 array([[ 9, 10, 11, 12,  1,  5,  7,  3]])]

Explanation about example

In [78]:
# Example 3 - breaking (to illustrate when it breaks)
a1=np.arange(1,10)
np.split(a1,4)

ValueError: array split does not result in an equal division

Explanation about example (why it breaks and how to fix it)

This error occurs when you try to split an array into sub-arrays that are not of equal size. In your case, it seems that you’re trying to split a 1D NumPy array with 9 elements into 4 sub-arrays.
To fix this error, you need to make sure that the number of elements in the array is evenly divisible by the number of sub-arrays.

Some closing comments about when to use this function.

## Conclusion

Summarize what was covered in this notebook, and where to go next

In your notebook, you have covered several important numpy array operations. Let's go through each operation and provide a summary:

Numpy Concatenation Arrays:
Numpy provides the np.concatenate() function to concatenate arrays along a specified axis. It allows you to combine arrays either along rows (axis=0) or along columns (axis=1). The arrays must have compatible shapes along the specified axis for successful concatenation.


Numpy Transpose Arrays:
The np.transpose() function or the .T attribute can be used to obtain the transpose of a numpy array. The transpose swaps the rows and columns of the array, effectively converting rows into columns and columns into rows.


Numpy Vertical Stack of Arrays:
Numpy provides np.vstack() to vertically stack arrays. It stacks arrays on top of each other, increasing the number of rows. The arrays must have the same number of columns along the axis you want to stack.

Numpy Horizontal Stack of Arrays:
For horizontal stacking of arrays, you can use np.hstack(). It concatenates arrays side by side, increasing the number of columns. The arrays must have the same number of rows along the axis you want to stack.

Numpy Split of Arrays:
The function np.split() can be used to split an array into multiple sub-arrays along a specified axis. It divides the array into equal-sized or equally divided parts.

These are the basic numpy array operations i've covered in your notebook.




## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...